#!/bin/bash
# create Abathur of Flask Python web server and launching it
docker run \
	-d --rm \
	-it \
	-v $(echo $HOME)/edu/tmp:/root \
	-p 3000:3000 \
	--name Abathur \
	python:2-slim bash

docker exec -it Abathur bash /root/run_web.sh
wait 30
docker stop Abathur
