#!/bin/bash
# Turn Aiur into a slave of the local swarm in which Char is leader.

docker-machine ssh Aiur "docker swarm join --token $(docker swarm join-token worker -q) $(docker-machine ip Char):2377"