#!/bin/bash
# Create an overlay-type internal network that you will name overmind.

#set env to docker manager
eval $(docker-machine env char)
docker network create --driver overlay --attachable overmind


#short info:
#before creating an overlay type network you should make a swarm. 
# And if you wanna to get overlay networks which works not only with swarm nodes, 
# you should add --attachable command when creating a network/

# docker-machine ssh char
# sudo -i